changelog:
  categories:
    - title: New Features 🎉
      labels:
        - feat
    - title: Bug Fixes 🛠
      labels:
        - fix
    - title: Chores 🛠
      labels:
        - chore
    - title: Docs 📝
      labels:
        - docs
    - title: Other Changes
      labels:
        - "*"
