changelog:
  exclude:
    labels:
      - docs
  categories:
    - title: New Features 🎉
      labels:
        - feat
    - title: Bug Fixes 🛠
      labels:
        - fix
    - title: Chores 🛠
      labels:
        - chore
    - title: Other Changes
      labels:
        - "*"
