name: ci

on:
  pull_request:

jobs:
  cargo-check:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.68.0
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt install libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev
      - run: mkdir ./app/kube-knots/dist
      - run: cargo check
        working-directory: ./app/kube-knots/src-tauri
  type-check:
    strategy:
      fail-fast: false
      matrix:
        app:
          - kube-knots
          - docs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install app dependencies
        run: yarn install
      - run: yarn workspace ${{ matrix.app }} run typecheck
  title-format:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            chore
          scopes: |
            deps
          requireScope: false
          wip: true
      - uses: actions/github-script@v6
        with:
          script: |
            const { title } = context.payload.pull_request;
            const label = title.split(':')[0]
            github.rest.issues.setLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [label]
            })
