name: ci

on:
  pull_request:

jobs:
  # TODO: fix this workflow, need to install a bunch of dependencies
  # cargo-check:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: 1.68.0
  #     - run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev
  #     - run: cargo check
  #       working-directory: ./app/kube-knots/src-tauri

  title-format:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            chore
          wip: true
      - uses: actions/github-script@v6
        with:
          script: |
            const { title } = context.payload.pull_request;
            const label = title.split(':')[0]
            github.rest.issues.setLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [label]
            })
